# Generated by Django 5.0.7 on 2024-11-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
